# Overridden default settings
# MUST have trailing slash
# for staging test, uncomment this
baseURL = "http://jitshappens.com/"
# baseURL = "http://austinjujitsu.com/"
languageCode = "en-us"
newContentEditor = "atom"
theme = "grid-side"
title = "Jits Happens - Brazilian Jiu-Jitsu"
copyright = "jits"

# Default settings, included here for reference. Not required.
archetypedir=               "archetype"
# hostname (and path) to the root, e.g. http=//spf13.com/
# baseURL=                    ""
# include content marked as draft
buildDrafts=                false
# include content with publishdate in the future
buildFuture=                false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs=               false
canonifyURLs=               false
# config file (default is path/config.yaml|json|toml)
config=                     "config.toml"
contentdir=                 "content"
dataDir=                    "data"
defaultExtension=           "html"
defaultLayout=              "post"
disableLiveReload=          false
# Do not build RSS files
disableRSS=                 false
# Do not build Sitemap file
disableSitemap=             false
# Build robots.txt file
enableRobotsTXT=            false
# Do not render 404 page
disable404=                 false
# edit new content with this editor, if provided
editor=                     ""
# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji=                false
footnoteAnchorPrefix=       ""
footnoteReturnLinkContents= ""
# google analytics tracking id for content.goverb.com
googleAnalytics=            "UA-286848-4"
# languageCode=               ""
layoutdir=                  "layouts"
# Enable Logging
log=                        false
# Log File path (if set, logging enabled automatically)
logFile=                    ""
# "yaml", "toml", "json"
metaDataFormat=             "toml"
# newContentEditor=           ""
# Don't sync modification time of files
noTimes=                    false
paginate=                   30
paginatePath=               "page"
# permalinks= NOT SURE WHAT DEFAULT IS
# Pluralize titles in lists using inflect
pluralizeListTitles=        true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames=      false
# filesystem path to write files to
publishdir=                 "../go-jitshappens/public"
# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax= false
# color-codes for highlighting derived from this style
pygmentsStyle=              "monokai"
# true= use pygments-css or false: color-codes directly
pygmentsUseClasses=         false
# default sitemap configuration map
#sitemap= NOT SURE WHAT DEFAULT IS
# filesystem path to read files relative from
source=                     ""
staticdir=                  "static"
# display memory and timing of different steps of the program
stepAnalysis=               false
# theme to use (located by default in /themes/THEMENAME/)
themesdir = "themes"
# Theme
# theme = ""
# Title
# title = ""
# if true, use /filename.html instead of /filename/
uglyURLs=                   false
# Do not make the url/path to lowercase
disablePathToLower=         false
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage=             false
# verbose output
verbose=                    false
# verbose logging
verboseLog=                 false
# watch filesystem for changes and recreate as needed
watch=                      true






# Optional Disqus commenting
disqusShortname = ""

[taxonomies]
tag = "tags"
topic = "topics"
coach = "coaches"
blog = "blogs"
doing-good = "doing-good"

# gridside The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
SectionPagesMenu = "Main"

[Menus.Main]

[[Menus.Main.One]]
name= "Hi"


[[Menus.Main.Two]]
name = "not working"

# Values under [params] will populate the .Site.Params variable for use in templates
[params]
title = "Jits Happens - Brazilian Jiu-Jitsu"

# Add social sharing
sharetwitter = true

# When set to true, will use infinite scrolling to load paginated content
# for posts, galleries, and projects
infinite_scroll = true
#
 # The post, project, and gallery sections can have infinite scroll turned
 # on/off individually. These values override the infinte_scroll option
 # above.
 #
 #[Params.Post]
 #
 #   infinite_scroll = false
 #
 #[Params.Project]
 #
 #   infinite_scroll = false
 #
 #[Params.Gallery]
 #
 #   infinite_scroll = false

 # override grid-side theme css with con11
 [Params.Overrides]
   cssOverride = true
   cssFile = "con11"


 #
 # Optionally specify the style for highlight.js to enable it, otherwise
 # you can use Pygments on the server side.
 #
 [Params.Highlight]

     style = "railscasts"

 #
 # Contains the main grid cell of your site (such as a picture of yourself)
 # along with your name, description, and email. Any empty field will
 # not be included. Not providing an image will use a color. Not specifying
 # the Header results in this cell not appearing in the site.
 #
 [Params.Header]

     # This is optional
     name = "Click or scroll down"

     logo = "v-outlinewhite.png"

     # This is optional
     description = ""

     tagline = " "
     tagline2 = "Brazilian Jiu-Jitsu, Ground Fighting, & Submission Grappling"


     # This is optional
     email = ""

  #   image = "img/jits-happens.png"

     # redirect on click of main logo
     redirectOnClick = true

     # Not providing this results in a color being used
     # image = "/img/verb-home-top.jpg"

     # This uses the CSS background-position, given the image above is set,
     # useful when you want to adjust where the background-image lands
     # image_position = "top"

     # This must be provided if the image above is not
     #color = "#FFF"

 #
 # Contains the footer of your main page and will also append items to
 # the end of your sidebar in non-homepage pages.
 #
 [Params.Footer]


    companyHomeURL = "http://jitshappens.com"
    target = "_self"

     #
     # Represents the list of icons and associated links to use in your
     # footer and sidebar. Your copyright information will always be
     # shown in the footer.
     #
     # The icon class is a font awesome classname.
     #
     #   e.g. twitter == "fa fa-twitter"
     #
     [[Params.Footer.List]]

    #     icon_class = "map-marker"
    #     icon_link = "https://goo.gl/G8FMu2"
    #     target = "_blank"

      [[Params.Footer.List]]

         icon_class = "rss"
         icon_link = "/blogs/jits-happens"
         target = "_self"


     [[Params.Footer.List]]

         icon_class = "twitter"
         icon_link = "http://twitter.com/davecthomas"
         # Links open in new tab
         target = "_blank"

     [[Params.Footer.List]]

         icon_class = "facebook"
         icon_link = "http://www.facebook.com/davecthomasatx"
         # Links open in new tab
         target = "_blank"

     [[Params.Footer.List]]

         icon_class = "youtube"
         icon_link = "https://www.youtube.com/channel/UCAz3ZyJFnQmCJl0PyVce_4A"
         # Links open in new tab
         target = "_blank"

     [[Params.Footer.List]]

         icon_class = "picture-o"
         icon_link = "https://get.google.com/u/3/albumarchive/111656665341965456714?source=pwa&pageId=none"
         # Links open in new tab
         target = "_blank"

#     [[Params.Footer.List]]
#
#         icon_class = "google-plus"
#         icon_link = "http://plus.google.com/+Austinjiujitsu1"
#         # Links open in new tab
#         target = "_blank"

#     [[Params.Footer.List]]
#
#        icon_class = "instagram"
#        icon_link = "http://www.instagram.com/davecthomas/"
#        # Links open in new tab
#        target = "_blank"

      [[Params.Footer.List]]

       icon_text = "BJJTech"
       icon_link = "http://www.bjjtech.com/"
       # Links open in new tab
       target = "_self"

# Post settings
[Params.Post]
      # The image to use as a background-image for the post full page
      image = ""
      author_image_path = "img/authors/"
 #
 # Contains the Cells representing the sections of your website. Each cell
 # contains the name of the cell, an image depicting what the content
 # represents, and a link to use when the cell is clicked.
 #
 # Not providing an image will use the color specified by 'color' as the
 # background color (default to #FFF).
 #
 # You can embed an icon using 'icon' to specify the classes to use
 # for the icon (such as 'fa fa-flag' when using font awesome).
 #
 # By default, each cell has a grid size of 1/3 (4 out of 12) for large
 # screens, 1/2 (6 out of 12) for medium screens, and 1 (12 out of 12) for
 # small screens. To change the cell's size per screen, use the properties
 # 'cell_large', 'cell_medium', and 'cell_small' respectively with a number
 # ranging from 1 to 12. Make sure that Cells have nubmers equalling 12
 # per row.
 #
 [Params.Cells]

    [[Params.Cells.List]]

       name = "About Dave"
       always_show_text = true
       grayscale = true
       link = "coaches/"
       image = "img/authors/dave-thomas.jpg"
       #image_position = "left"


   [[Params.Cells.List]]

     name = "Dave's techniques at BJJTech.com"
     always_show_text = true
     grayscale = true
     outlink = "http://bjjtech.com"
     image = ""

    [[Params.Cells.List]]

        name = "Dave's jits writings"
        always_show_text = true
        grayscale = true
        outlink = "http://jitshappens.com"
        image = ""

     [[Params.Cells.List]]

         # The name to use with the cell, shows up on hover
         name = "The Basics"

         # The link to associate with the cell, used when clicked
         # do not start with /
         link = "post/"

         # The image to use as a background-image for the cell
         image = ""

         # This uses the CSS background-position, given the image above is
         # set, useful when you want to adjust where the background-image
         # lands
         #image_position = "top"

         # The color to use as a fallback if an image is not provided
         #color = "#eceded"

         # Grays out the image (if provided), the image will be restored
         # to normal color on hover
         grayscale = true

         # Disables the normal cell highlight on hover
         #no_highlight = true

         # Normally, a cell only shows text (its name) on hover, setting
         # this to true results in the cell always showing its text
         # and also using a dark overlay to make the white text be more
         # visible
         always_show_text = true

         # Grays out the cell and disables click functionality on it
         #disable = true

     [[Params.Cells.List]]

       name = "Doing Good"
       always_show_text = true
       grayscale = true
       link = "doing-good/"
       image = ""

     [[Params.Cells.List]]
        # The I is capitalized on purpose, since Pythia's lower case I is ugly
         name = "Topics"
         always_show_text = true
         grayscale = true
         link = "topics/"
         image = ""


    [[Params.Cells.List]]

       name = "Tags"
       always_show_text = true
       grayscale = true
       link = "tags/"
       image = "img/team.jpg"
